import 'bloc/signup_one_bloc.dart';import 'models/signup_one_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/core/utils/validation_functions.dart';import 'package:organixxx/widgets/custom_elevated_button.dart';import 'package:organixxx/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SignupOneScreen extends StatelessWidget {SignupOneScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SignupOneBloc>(create: (context) => SignupOneBloc(SignupOneState(signupOneModelObj: SignupOneModel()))..add(SignupOneInitialEvent()), child: SignupOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 20.v), child: Column(children: [_buildUserName1(context), SizedBox(height: 20.v), _buildPassword(context), SizedBox(height: 20.v), _buildConfirmpassword(context), Spacer(), SizedBox(height: 98.v), _buildNext(context)]))))); } 
/// Section Widget
Widget _buildUserName(BuildContext context) { return BlocSelector<SignupOneBloc, SignupOneState, TextEditingController?>(selector: (state) => state.userNameController, builder: (context, userNameController) {return CustomTextFormField(width: 335.h, controller: userNameController, hintText: "lbl_enter_username".tr, alignment: Alignment.bottomCenter, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildUserName1(BuildContext context) { return SizedBox(height: 352.v, width: 335.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgLogo1, height: 202.v, width: 158.h, alignment: Alignment.topCenter), CustomImageView(imagePath: ImageConstant.imgPureOrganic1, height: 212.v, width: 266.h, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 44.v)), _buildUserName(context)])); } 
/// Section Widget
Widget _buildPassword(BuildContext context) { return BlocBuilder<SignupOneBloc, SignupOneState>(builder: (context, state) {return CustomTextFormField(controller: state.passwordController, hintText: "lbl_enter_password".tr, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {context.read<SignupOneBloc>().add(ChangePasswordVisibilityEvent(value: !state.isShowPassword));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgEyeoff, height: 14.adaptSize, width: 14.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 50.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword, contentPadding: EdgeInsets.only(left: 22.h, top: 12.v, bottom: 12.v));}); } 
/// Section Widget
Widget _buildConfirmpassword(BuildContext context) { return BlocBuilder<SignupOneBloc, SignupOneState>(builder: (context, state) {return CustomTextFormField(controller: state.confirmpasswordController, hintText: "msg_confirm_password".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {context.read<SignupOneBloc>().add(ChangePasswordVisibilityEvent1(value: !state.isShowPassword1));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgEyeoff, height: 14.adaptSize, width: 14.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 50.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword1, contentPadding: EdgeInsets.only(left: 22.h, top: 13.v, bottom: 13.v));}); } 
/// Section Widget
Widget _buildNext(BuildContext context) { return CustomElevatedButton(height: 50.v, text: "lbl_next".tr, onPressed: () {onTapNext(context);}); } 
/// Navigates to the signupTwoScreen when the action is triggered.
onTapNext(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signupTwoScreen, ); } 
 }
