import 'bloc/my_cart_product_bloc.dart';import 'models/my_cart_product_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/widgets/app_bar/appbar_leading_image.dart';import 'package:organixxx/widgets/app_bar/appbar_subtitle.dart';import 'package:organixxx/widgets/app_bar/custom_app_bar.dart';class MyCartProductScreen extends StatelessWidget {const MyCartProductScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MyCartProductBloc>(create: (context) => MyCartProductBloc(MyCartProductState(myCartProductModelObj: MyCartProductModel()))..add(MyCartProductInitialEvent()), child: MyCartProductScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<MyCartProductBloc, MyCartProductState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 70.v), decoration: AppDecoration.fillGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 35.v), _buildSixty(context), Spacer(), _buildFiftyEight(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 23.h, top: 43.v, bottom: 24.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_vegetable2".tr, margin: EdgeInsets.only(top: 44.v, bottom: 16.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildSixty(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 15.v), decoration: AppDecoration.fillOnPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(right: 100.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTomatoes1, height: 43.v, width: 59.h, margin: EdgeInsets.only(top: 6.v)), Padding(padding: EdgeInsets.only(left: 11.h, bottom: 31.v), child: Text("msg_fresh_organic_tomato2".tr, style: CustomTextStyles.bodySmall12))])), SizedBox(height: 5.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 70.h, right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 18.v, width: 45.h, margin: EdgeInsets.only(top: 3.v, bottom: 5.v), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Text("lbl_30_00".tr, style: CustomTextStyles.labelLargeBlack900)), CustomImageView(imagePath: ImageConstant.imgCurrencyRupee, height: 14.adaptSize, width: 14.adaptSize, alignment: Alignment.centerLeft)])), SizedBox(height: 27.v, width: 74.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 24.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder2), child: Container(height: 24.v, width: 23.h, decoration: BoxDecoration(color: appTheme.blueGray100, border: Border.all(color: appTheme.gray50001, width: 1.h))))), Align(alignment: Alignment.center, child: Container(width: 60.h, margin: EdgeInsets.symmetric(horizontal: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl".tr, style: CustomTextStyles.bodyLargeGray50001_1), Text("lbl_0".tr, style: CustomTextStyles.bodyLarge16), Text("lbl2".tr, style: theme.textTheme.bodyLarge)])))]))]))), SizedBox(height: 3.v)])); } 
/// Section Widget
Widget _buildFiftyEight(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 14.v), decoration: AppDecoration.fillOnPrimary, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 4.v, bottom: 10.v), child: Text("msg_1_item_in_vegetable".tr, style: CustomTextStyles.bodyMediumGray50001)), Container(height: 27.v, width: 69.h, margin: EdgeInsets.only(bottom: 8.v), child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.centerRight, child: Text("lbl_30_00".tr, style: CustomTextStyles.titleMediumSemiBold18)), CustomImageView(imagePath: ImageConstant.imgCurrencyRupee, height: 21.v, width: 22.h, alignment: Alignment.centerLeft)]))])); } 
/// Navigates to the myCartEmptyScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myCartEmptyScreen, ); } 
 }
