import 'bloc/deliver_to_new_address_one_bloc.dart';import 'models/deliver_to_new_address_one_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/widgets/app_bar/appbar_leading_image.dart';import 'package:organixxx/widgets/app_bar/appbar_subtitle.dart';import 'package:organixxx/widgets/app_bar/custom_app_bar.dart';import 'package:organixxx/widgets/custom_drop_down.dart';import 'package:organixxx/widgets/custom_elevated_button.dart';import 'package:organixxx/widgets/custom_radio_button.dart';import 'package:organixxx/widgets/custom_text_form_field.dart';class DeliverToNewAddressOneScreen extends StatelessWidget {const DeliverToNewAddressOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<DeliverToNewAddressOneBloc>(create: (context) => DeliverToNewAddressOneBloc(DeliverToNewAddressOneState(deliverToNewAddressOneModelObj: DeliverToNewAddressOneModel()))..add(DeliverToNewAddressOneInitialEvent()), child: DeliverToNewAddressOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 70.v), padding: EdgeInsets.symmetric(vertical: 16.v), decoration: AppDecoration.fillGray, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 3.v), _buildGroup357(context), SizedBox(height: 19.v), _buildAddress(context), Spacer(), CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.symmetric(horizontal: 53.h), buttonStyle: CustomButtonStyles.fillPrimaryTL5, buttonTextStyle: CustomTextStyles.titleLargeOnPrimary, onPressed: () {onTapContinue(context);})])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 23.h, top: 43.v, bottom: 24.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_deliver_to".tr), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildGroup357(BuildContext context) { return BlocBuilder<DeliverToNewAddressOneBloc, DeliverToNewAddressOneState>(builder: (context, state) {return state.deliverToNewAddressOneModelObj!.radioList.isNotEmpty ? Column(children: [Padding(padding: EdgeInsets.only(left: 20.h, top: 19.v, right: 184.h), child: CustomRadioButton(text: "msg_current_location".tr, value: state.deliverToNewAddressOneModelObj?.radioList[0] ?? "", groupValue: state.radioGroup, onChange: (value) {context.read<DeliverToNewAddressOneBloc>().add(ChangeRadioButtonEvent(value: value));})), Padding(padding: EdgeInsets.fromLTRB(20.h, 17.v, 213.h, 17.v), child: CustomRadioButton(text: "lbl_new_adderss".tr, value: state.deliverToNewAddressOneModelObj?.radioList[2] ?? "", groupValue: state.radioGroup, onChange: (value) {context.read<DeliverToNewAddressOneBloc>().add(ChangeRadioButtonEvent(value: value));}))]) : Container();}); } 
/// Section Widget
Widget _buildAddress(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 21.v), decoration: AppDecoration.fillOnPrimary, child: Column(children: [BlocSelector<DeliverToNewAddressOneBloc, DeliverToNewAddressOneState, TextEditingController?>(selector: (state) => state.addressController, builder: (context, addressController) {return CustomTextFormField(controller: addressController, hintText: "lbl_address_line_1".tr);}), SizedBox(height: 16.v), BlocSelector<DeliverToNewAddressOneBloc, DeliverToNewAddressOneState, TextEditingController?>(selector: (state) => state.addressController1, builder: (context, addressController1) {return CustomTextFormField(controller: addressController1, hintText: "lbl_address_line_2".tr, textInputAction: TextInputAction.done);}), SizedBox(height: 16.v), BlocSelector<DeliverToNewAddressOneBloc, DeliverToNewAddressOneState, DeliverToNewAddressOneModel?>(selector: (state) => state.deliverToNewAddressOneModelObj, builder: (context, deliverToNewAddressOneModelObj) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 13.v, 6.h, 13.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdropdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_city".tr, items: deliverToNewAddressOneModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<DeliverToNewAddressOneBloc>().add(ChangeDropDownEvent(value: value));});}), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [BlocSelector<DeliverToNewAddressOneBloc, DeliverToNewAddressOneState, DeliverToNewAddressOneModel?>(selector: (state) => state.deliverToNewAddressOneModelObj, builder: (context, deliverToNewAddressOneModelObj) {return CustomDropDown(width: 159.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 13.v, 6.h, 13.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdropdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_state".tr, items: deliverToNewAddressOneModelObj?.dropdownItemList1 ?? [], onChanged: (value) {context.read<DeliverToNewAddressOneBloc>().add(ChangeDropDown1Event(value: value));});}), SizedBox(height: 50.v, width: 160.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 23.h), child: Text("lbl_pincode".tr, style: CustomTextStyles.bodyLargeGreen100))), Align(alignment: Alignment.center, child: Container(height: 50.v, width: 160.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(15.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h))))]))])])); } 
/// Navigates to the myCartEmptyScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myCartEmptyScreen, ); } 
/// Navigates to the myCartEmptyScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myCartEmptyScreen, ); } 
 }
