import 'bloc/profile_address_bloc.dart';import 'models/profile_address_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/widgets/app_bar/appbar_leading_image.dart';import 'package:organixxx/widgets/app_bar/appbar_subtitle.dart';import 'package:organixxx/widgets/app_bar/custom_app_bar.dart';import 'package:organixxx/widgets/custom_drop_down.dart';import 'package:organixxx/widgets/custom_text_form_field.dart';class ProfileAddressScreen extends StatelessWidget {const ProfileAddressScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ProfileAddressBloc>(create: (context) => ProfileAddressBloc(ProfileAddressState(profileAddressModelObj: ProfileAddressModel()))..add(ProfileAddressInitialEvent()), child: ProfileAddressScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray100, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 21.v), child: Column(children: [_buildSeventyFive(context), SizedBox(height: 33.v), _buildSeventyFour(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 20.h, top: 41.v, bottom: 26.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_address".tr), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildSeventyFive(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 19.v), decoration: AppDecoration.fillOnPrimary, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("msg_current_location".tr, style: theme.textTheme.titleMedium), SizedBox(height: 4.v), Text("msg_delivering_to_kakkanad".tr, style: theme.textTheme.bodyMedium), SizedBox(height: 2.v)])); } 
/// Section Widget
Widget _buildSeventyFour(BuildContext context) { return Container(padding: EdgeInsets.all(19.h), decoration: AppDecoration.fillOnPrimary, child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_address".tr, style: theme.textTheme.titleMedium)), SizedBox(height: 6.v), BlocSelector<ProfileAddressBloc, ProfileAddressState, TextEditingController?>(selector: (state) => state.addressController, builder: (context, addressController) {return CustomTextFormField(controller: addressController, hintText: "lbl_address_line_1".tr);}), SizedBox(height: 16.v), BlocSelector<ProfileAddressBloc, ProfileAddressState, TextEditingController?>(selector: (state) => state.addressController1, builder: (context, addressController1) {return CustomTextFormField(controller: addressController1, hintText: "lbl_address_line_2".tr, textInputAction: TextInputAction.done);}), SizedBox(height: 16.v), BlocSelector<ProfileAddressBloc, ProfileAddressState, ProfileAddressModel?>(selector: (state) => state.profileAddressModelObj, builder: (context, profileAddressModelObj) {return CustomDropDown(icon: Container(margin: EdgeInsets.fromLTRB(30.h, 13.v, 6.h, 13.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdropdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_city".tr, items: profileAddressModelObj?.dropdownItemList ?? [], onChanged: (value) {context.read<ProfileAddressBloc>().add(ChangeDropDownEvent(value: value));});}), SizedBox(height: 16.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [BlocSelector<ProfileAddressBloc, ProfileAddressState, ProfileAddressModel?>(selector: (state) => state.profileAddressModelObj, builder: (context, profileAddressModelObj) {return CustomDropDown(width: 159.h, icon: Container(margin: EdgeInsets.fromLTRB(30.h, 13.v, 6.h, 13.v), child: CustomImageView(imagePath: ImageConstant.imgArrowdropdown, height: 24.adaptSize, width: 24.adaptSize)), hintText: "lbl_state".tr, items: profileAddressModelObj?.dropdownItemList1 ?? [], onChanged: (value) {context.read<ProfileAddressBloc>().add(ChangeDropDown1Event(value: value));});}), SizedBox(height: 50.v, width: 160.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 23.h), child: Text("lbl_pincode".tr, style: CustomTextStyles.bodyLargeGreen100))), Align(alignment: Alignment.center, child: Container(height: 50.v, width: 160.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(15.h), border: Border.all(color: theme.colorScheme.primary, width: 1.h))))]))]), SizedBox(height: 5.v)])); } 
/// Navigates to the profileScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
 }
