import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/stbannertwentyone1_item_model.dart';import '../models/vegetables1_item_model.dart';import '../models/artboardeleven1_item_model.dart';import '../models/bannerbiggone1_item_model.dart';import '../models/productdetails_item_model.dart';import 'package:organixxx/presentation/home_screen/models/home_model.dart';part 'home_event.dart';part 'home_state.dart';/// A bloc that manages the state of a Home according to the event that is dispatched to it.
class HomeBloc extends Bloc<HomeEvent, HomeState> {HomeBloc(HomeState initialState) : super(initialState) { on<HomeInitialEvent>(_onInitialize); }

List<Stbannertwentyone1ItemModel> fillStbannertwentyone1ItemList() { return List.generate(1, (index) => Stbannertwentyone1ItemModel()); } 
List<Vegetables1ItemModel> fillVegetables1ItemList() { return [Vegetables1ItemModel(vegetables: "Vegetables", vegetablesImage: ImageConstant.imgBasketFullVegetables), Vegetables1ItemModel(vegetables: "Meat", vegetablesImage: ImageConstant.imgWholeChickenS)]; } 
List<Artboardeleven1ItemModel> fillArtboardeleven1ItemList() { return [Artboardeleven1ItemModel(artboardEleven: ImageConstant.imgArtboard11), Artboardeleven1ItemModel(artboardEleven: ImageConstant.imgOrangeBanner1)]; } 
List<Bannerbiggone1ItemModel> fillBannerbiggone1ItemList() { return List.generate(1, (index) => Bannerbiggone1ItemModel()); } 
List<ProductdetailsItemModel> fillProductdetailsItemList() { return [ProductdetailsItemModel(twentyFive: "-25%", productName: "Fresh Cashew \r\n500g", productPrice: "400", productImage: ImageConstant.imgCashews1, quantityMinus: "-", quantityNumber: "1", quantityPlus: "+")]; } 
_onInitialize(HomeInitialEvent event, Emitter<HomeState> emit, ) async  { emit(state.copyWith(searchController: TextEditingController(), sliderIndex: 0, sliderIndex1: 0, sliderIndex2: 0)); emit(state.copyWith(homeModelObj: state.homeModelObj?.copyWith(stbannertwentyone1ItemList: fillStbannertwentyone1ItemList(), vegetables1ItemList: fillVegetables1ItemList(), artboardeleven1ItemList: fillArtboardeleven1ItemList(), bannerbiggone1ItemList: fillBannerbiggone1ItemList(), productdetailsItemList: fillProductdetailsItemList()))); } 
 }
