import 'bloc/app_setting_bloc.dart';import 'models/app_setting_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/widgets/app_bar/appbar_leading_image.dart';import 'package:organixxx/widgets/app_bar/appbar_subtitle.dart';import 'package:organixxx/widgets/app_bar/custom_app_bar.dart';import 'package:organixxx/widgets/custom_switch.dart';class AppSettingScreen extends StatelessWidget {const AppSettingScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AppSettingBloc>(create: (context) => AppSettingBloc(AppSettingState(appSettingModelObj: AppSettingModel()))..add(AppSettingInitialEvent()), child: AppSettingScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 42.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildNotification(context), SizedBox(height: 15.v), _buildDarkMode(context), SizedBox(height: 14.v), Text("lbl_language".tr, style: CustomTextStyles.bodyLarge16), SizedBox(height: 15.v), Text("lbl_about_us".tr, style: CustomTextStyles.bodyLarge16), SizedBox(height: 12.v), Text("msg_terms_and_condition".tr, style: CustomTextStyles.bodyLarge16), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 20.h, top: 41.v, bottom: 26.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_settings".tr, margin: EdgeInsets.only(top: 42.v, bottom: 18.v)), styleType: Style.bgShadow); } 
/// Section Widget
Widget _buildNotification(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_notification".tr, style: CustomTextStyles.bodyLarge16), BlocSelector<AppSettingBloc, AppSettingState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(value: isSelectedSwitch, onChange: (value) {context.read<AppSettingBloc>().add(ChangeSwitchEvent(value: value));});})])); } 
/// Section Widget
Widget _buildDarkMode(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_dark_mode".tr, style: CustomTextStyles.bodyLarge16), BlocSelector<AppSettingBloc, AppSettingState, bool?>(selector: (state) => state.isSelectedSwitch1, builder: (context, isSelectedSwitch1) {return CustomSwitch(margin: EdgeInsets.only(top: 2.v), value: isSelectedSwitch1, onChange: (value) {context.read<AppSettingBloc>().add(ChangeSwitch1Event(value: value));});})])); } 
/// Navigates to the profileScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
 }
