import 'bloc/signup_two_bloc.dart';import 'models/signup_two_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/core/utils/validation_functions.dart';import 'package:organixxx/widgets/custom_elevated_button.dart';import 'package:organixxx/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class SignupTwoScreen extends StatelessWidget {SignupTwoScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<SignupTwoBloc>(create: (context) => SignupTwoBloc(SignupTwoState(signupTwoModelObj: SignupTwoModel()))..add(SignupTwoInitialEvent()), child: SignupTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.all(20.h), child: Column(children: [SizedBox(height: 308.v, width: 266.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgLogo1, height: 202.v, width: 158.h, alignment: Alignment.topCenter), CustomImageView(imagePath: ImageConstant.imgPureOrganic1, height: 212.v, width: 266.h, alignment: Alignment.bottomCenter)])), SizedBox(height: 53.v), BlocSelector<SignupTwoBloc, SignupTwoState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(controller: emailController, hintText: "lbl_email_id".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});}), SizedBox(height: 23.v), BlocSelector<SignupTwoBloc, SignupTwoState, TextEditingController?>(selector: (state) => state.phoneNumberController, builder: (context, phoneNumberController) {return CustomTextFormField(controller: phoneNumberController, hintText: "lbl_phone_number".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});}), Spacer(), SizedBox(height: 98.v), CustomElevatedButton(height: 50.v, text: "lbl_next".tr, onPressed: () {onTapNext(context);})]))))); } 
/// Navigates to the signupThreeScreen when the action is triggered.
onTapNext(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signupThreeScreen, ); } 
 }
