import '../my_order_screen/widgets/orderdetails_item_widget.dart';import 'bloc/my_order_bloc.dart';import 'models/my_order_model.dart';import 'models/orderdetails_item_model.dart';import 'package:flutter/material.dart';import 'package:organixxx/core/app_export.dart';import 'package:organixxx/widgets/app_bar/appbar_leading_image.dart';import 'package:organixxx/widgets/app_bar/appbar_subtitle.dart';import 'package:organixxx/widgets/app_bar/custom_app_bar.dart';class MyOrderScreen extends StatelessWidget {const MyOrderScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MyOrderBloc>(create: (context) => MyOrderBloc(MyOrderState(myOrderModelObj: MyOrderModel()))..add(MyOrderInitialEvent()), child: MyOrderScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray100, appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(top: 6.v), child: BlocSelector<MyOrderBloc, MyOrderState, MyOrderModel?>(selector: (state) => state.myOrderModelObj, builder: (context, myOrderModelObj) {return ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 6.v);}, itemCount: myOrderModelObj?.orderdetailsItemList.length ?? 0, itemBuilder: (context, index) {OrderdetailsItemModel model = myOrderModelObj?.orderdetailsItemList[index] ?? OrderdetailsItemModel(); return OrderdetailsItemWidget(model, onTapImgDetails: () {onTapImgDetails(context);});});})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgIconlyLightOu, margin: EdgeInsets.only(left: 20.h, top: 41.v, bottom: 26.v), onTap: () {onTapIconlyLightOu(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_my_order".tr, margin: EdgeInsets.only(top: 42.v, bottom: 18.v)), styleType: Style.bgShadow); } 
/// Navigates to the myCartProductOneScreen when the action is triggered.
onTapImgDetails(BuildContext context) { NavigatorService.pushNamed(AppRoutes.myCartProductOneScreen); } 
/// Navigates to the profileScreen when the action is triggered.
onTapIconlyLightOu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
 }
