import 'package:equatable/equatable.dart';import 'package:flutter/material.dart';import '/core/app_export.dart';import '../models/stbannertwentyone_item_model.dart';import '../models/vegetables_item_model.dart';import '../models/artboardeleven_item_model.dart';import '../models/productitem_item_model.dart';import '../models/bannerbiggone_item_model.dart';import '../models/productcard_item_model.dart';import 'package:organixxx/presentation/home_one_page/models/home_one_model.dart';part 'home_one_event.dart';part 'home_one_state.dart';/// A bloc that manages the state of a HomeOne according to the event that is dispatched to it.
class HomeOneBloc extends Bloc<HomeOneEvent, HomeOneState> {HomeOneBloc(HomeOneState initialState) : super(initialState) { on<HomeOneInitialEvent>(_onInitialize); }

List<StbannertwentyoneItemModel> fillStbannertwentyoneItemList() { return List.generate(1, (index) => StbannertwentyoneItemModel()); } 
List<VegetablesItemModel> fillVegetablesItemList() { return [VegetablesItemModel(vegetables: "Vegetables", vegetablesImage: ImageConstant.imgBasketFullVegetables), VegetablesItemModel(vegetables: "Meat", vegetablesImage: ImageConstant.imgWholeChickenS)]; } 
List<ArtboardelevenItemModel> fillArtboardelevenItemList() { return List.generate(1, (index) => ArtboardelevenItemModel()); } 
List<ProductitemItemModel> fillProductitemItemList() { return [ProductitemItemModel(productImage: ImageConstant.imgTomatoes1, productName: "Fresh Organic Tomato \r\n500g", productQuantity: "30", productMinus: "-", productNumber: "1", productPlus: "+"), ProductitemItemModel(productImage: ImageConstant.imgOrangeJuicyRi, productName: "Fresh Organic Oragne \r\n500g", productQuantity: "50", productMinus: "-", productNumber: "1", productPlus: "+")]; } 
List<BannerbiggoneItemModel> fillBannerbiggoneItemList() { return List.generate(1, (index) => BannerbiggoneItemModel()); } 
List<ProductcardItemModel> fillProductcardItemList() { return [ProductcardItemModel(twentyFive: "-25%", productName: "Fresh Cashew \r\n500g", productPrice: "400", productImage: ImageConstant.imgCashews1, discountText: "-", discountNumber: "1", discountText1: "+")]; } 
_onInitialize(HomeOneInitialEvent event, Emitter<HomeOneState> emit, ) async  { emit(state.copyWith(searchController: TextEditingController(), sliderIndex: 0, sliderIndex1: 0, sliderIndex2: 0)); emit(state.copyWith(homeOneModelObj: state.homeOneModelObj?.copyWith(stbannertwentyoneItemList: fillStbannertwentyoneItemList(), vegetablesItemList: fillVegetablesItemList(), artboardelevenItemList: fillArtboardelevenItemList(), productitemItemList: fillProductitemItemList(), bannerbiggoneItemList: fillBannerbiggoneItemList(), productcardItemList: fillProductcardItemList()))); } 
 }
